### PR TITLE
Add endpoint to parameter requests

### PR DESCRIPTION
**Pull request by c-martinez**
Allow to provide endpoint as request url parameter. This overrides default value in config.ini and endpoint parameter on query (`#+ endpoint:`)

```
curl -X GET --header "Accept: application/json" "http://grlc.io/api/user/repo/query?endpoint=http://example.com/sparql"
```

Might be good to document this in a bit more detail.

### CODE REVIEW

**Comment by albertmeronyo** [comment]
You're a hero @c-martinez !

**Comment by albertmeronyo** [comment]
Hi @c-martinez 
This PR seems to have introduced a bug in the order of preference in which old queries (i.e. wituout having the #+ no_endpoint_url attribute) behave.
For example http://grlc.io/api/peta-pico/nanopub-api returns zero results because it goes to dbpedia.org (default endpoint) instead of the endpoint specified in the endpoints.txt file (it uses no #+ endpoint attribute). But if the sparql endpoint is not supplied as parameter, the old order of preference should be maintained, right?
Could you take a look at it asap? Otherwise I'll try to fix it. Thanks!

**Comment by albertmeronyo** [comment]
Sorry, I meant http://grlc.io/api/peta-pico/nanopub-api/get_all_indexes in the previous example

**Comment by c-martinez** [comment]
Hey @albertmeronyo -- I think bug might have been introduced a bit earlier. I'm submitting [PR](#103) which should solve this issue.

**Pull request merged**
