### PR TITLE
Pip installable

### PR DESCRIPTION
**Pull request by c-martinez**
Modified so it can be pip installable.

So grlc is installable directly from github via `pip` like this:
```$ pip install git+https://github.com/c-martinez/grlc.git@pip-installable```

And then someone (like me) can import it into their own project and use, for instance `build_spec`:
```from grlc.utils import build_spec```

After pip installing, flask server can be run like this:
```$ grlc-server ```

or gunicorn version like this (still need to have a `gunicorn_config.py`):
```$ gunicorn -c gunicorn_config.py grlc.server:app```

### CODE REVIEW

**Comment by albertmeronyo** [comment]
Thanks for these @c-martinez !

Some questions:
- Why did you move all statics and templates into /src/? Is this required by pip?
- We might still want to be virtualenv compatible, so we shouldn't have a /bin/ dir. Is this required by pip too?
- We always spell it 'grlc' in low caps ;)

Thanks again for the contribs!

**Comment by c-martinez** [comment]
- Why did you move all statics and templates into /src/? Is this required by pip?
Files on `src/` are copied as part of the package when installed via pip. So yes, it is required by pip.

 - We might still want to be virtualenv compatible, so we shouldn't have a /bin/ dir. Is this required by pip too?
Things in `bin/` (in this case the `grlc-server` script) get copied to `bin/` in the virtualenv. I don't think this makes it incompatible with virtualenv (in fact, I am testing it in a virtualenv). But if we are against it being under `bin/`, it can be changed to any other location we define on setup.py.

 - We always spell it 'grlc' in low caps ;)
Ah! I was not sure about that -- I'll change that.

**Comment by albertmeronyo** [comment]
Oh I see the server launching code is also under src/, so that shouldn't be a problem.
Fine with leaving grlc-server under bin/ too if that doesn't affect virtualenv.
If you %s/GRLC/grlc/g I'll merge right away :-)

Thanks!

**Comment by c-martinez** [comment]
:+1: thank you sr!

**Pull request merged**
