### PR TITLE
Pip installable up to python 3.9

### PR DESCRIPTION
**Pull request by c-martinez**
Tested for Pythons 3.6.15 | 3.7.16 | 3.8.16 | 3.9.16 as follows:

```bash
virtualenv py3X --python python3X
source py3X/bin/activate
pip install .
pip install -r requirements-test.txt
pytest tests/
deactivate
```
(where the X is the python version 6, 7, 8 or 9)

### CODE REVIEW

**Comment by c-martinez** [comment]
Addresses #386

**Comment by c-martinez** [comment]
As part of testing this, we should make sure Github Action for testing passes tests for all versions of Python included here (6 to 9)

**Comment by rapw3k** [comment]
Hi @c-martinez i was testing for python 3.9 and it build ok...

**Comment by c-martinez** [comment]
Great, thanks for testing @rapw3k , good to know it not only works on my computer :-)

**Comment by c-martinez** [comment]
It looks like it is building properly [in GitHub actions](https://github.com/c-martinez/grlc/actions/runs/4091270187) for all versions.

I think we can merge this, unless you see any issues @albertmeronyo ?

**Pull request merged**
