### PR TITLE
Fetch grlc-ready repos

### PR DESCRIPTION
**Pull request by c-martinez**
Small improvement on for the front-end:

You can enter your github username, and grlc will figure out which of your repos is can be used to generate an api.

### CODE REVIEW

**Comment by albertmeronyo** [comment]
Thanks for the PR @c-martinez !
Two things:
- The isSparql() function should also recognize files with the .sparql extension for consistency with grlc
- How does the JS work interaction-wise? Does it look automatically on whether you're logged into GitHub, or does it need the user to provide their username?

Thanks again!

**Comment by c-martinez** [comment]
Well spotted @albertmeronyo -- added `.sparql` as valid file.

Unfortunately, user still has to enter their github username (I could not make it so it detects it automatically).

**Comment by rlzijdeman** [comment]
@c-martinez  sorry to do it like this, but could you please send me an email (I can't find your mail address!) I'm richard <dot> zijdeman <@> iisg <dot> nl

**Comment by c-martinez** [comment]
Won't merge.

**Pull request closed without merging**
