### PR TITLE
Adding SPARQL Update

### PR DESCRIPTION
**Pull request by GenEars**
Relates to https://github.com/CLARIAH/grlc/issues/377 and https://github.com/CLARIAH/grlc/pull/384#issuecomment-1378638201

### CODE REVIEW

**Comment by c-martinez** [comment]
Hey @GenEars I think this PR, similar to #390, we might need to create a new branch with only the relevant changes. I am leaving this as a draft PR until a new branch has been created. Does that sound ok to you?

**Comment by GenEars** [comment]
Hello @c-martinez. Yes, a new branch of the "*dev_sparql_update*" kind seems to make the merge easier.

**Comment by c-martinez** [comment]
Great, I will do that :-)

**Comment by GenEars** [comment]
> @GenEars -- am I right to think that the main change is in `swagger.py` [lines 318-320](https://github.com/CLARIAH/grlc/pull/388/files#diff-62a76df7612fede7ee35af0ec179cf2899701fb59396910ecd3d4d05c10eb377R318-R320)?

Hello @c-martinez, yes [lines 318-320](https://github.com/CLARIAH/grlc/pull/388/files#diff-62a76df7612fede7ee35af0ec179cf2899701fb59396910ecd3d4d05c10eb377R318-R320) are key for the Swagger, but we also have to consider handling the query method (i.e. GET vs POST) in [lines 97-102 (utils.py)](https://github.com/Orange-OpenSource/grlc/blob/9e3e7b818252b750081d57b803c3464a50d3ddc2/grlc_fork/utils.py#L99) and [lines 215-219 (utils.py)](https://github.com/Orange-OpenSource/grlc/blob/9e3e7b818252b750081d57b803c3464a50d3ddc2/grlc_fork/utils.py#L215) as `#+ method: POST` is involved in graph update queries.

**Comment by c-martinez** [comment]
Right, yes that should also be taken into account. Is there a restriction that updates should always be sent via POST method?

Also,  do you have by any chance a query we could use for testing in the test repo?

**Comment by c-martinez** [comment]
Hi @GenEars! I've created #400, which (I think) incorporates the relevant changes of this PR.

I will close this PR, and if you could have a look at #400 and let me know if you think it is ok, that would be fantastic!

**Pull request closed without merging**
