### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by mwigham**
For some fixes to installing under python 3

### CODE REVIEW

**Comment by c-martinez** [comment]
Hi @mwigham -- thanks for these changes! I'm going over them quickly to check if we can merge them.

Couple of comments:

 - Perhaps instead of removing special characters in `README.md` we should make sure they are read in properly in `setup.py` by using `open(..., encoding='utf-8')`
 - I think this patch changes `LOG_DEBUG_MODE` to always be `True` instead of configurable via `config.ini` -- was there any reasoning for this?
 - It looks like keeping support for python2 is starting to cost too many patches everywhere. @albertmeronyo -- what do you think? Can we drop python2 support (and maybe add a tag for the last version which supports python2)?

**Comment by mwigham** [comment]
Thanks Carlos, that would be great as we are really looking forward to being able to use pip to install grlc.
Reading the characters in properly would definitely be better. I wasn't sure where it was failing, that's why I took the easy way out.
I didn't (knowingly) change anything for the LOG_DEBUG_MODE, so no, no reasoning for this ;)

**Comment by c-martinez** [comment]
Hi @mwigham -- I applied some of your changes along with some other changes and merged to dev branch. Hopefully, everything should work with the next release. Thanks for your help!

**Comment by mwigham** [comment]
@c-martinez That's great, thanks! What is the timeline for the next release, and will pypi be updated then too?

**Comment by c-martinez** [comment]
As soon as @albertmeronyo gives his thumbs up, we can merge #204 into master and make a release -- pypi gets updated automatically at that point.

**Pull request closed without merging**
